create table if not exists students (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  major text,
  universities text,
  portal text default 'OUAC',
  status text default 'Drafting',
  docs text default 'Missing',
  pal text default 'N/A',
  deadline date,
  notes text,
  checklist jsonb default '[]'::jsonb
);

create table if not exists applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_id bigint references students(id) on delete cascade not null,
  school_name text not null,
  program text,
  status text default 'Drafting',
  deadline date,
  app_fee text,
  tuition text,
  housing text,
  meal_plan text,
  other_expenses text,
  scholarship_info text,
  requirements text,
  notes text
);

-- Enable RLS
alter table students enable row level security;
alter table applications enable row level security;

-- Create open policy for this internal tool
create policy "Allow all access" on students for all using (true) with check (true);
create policy "Allow all access" on applications for all using (true) with check (true);
