create table if not exists universities (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  location text,
  deadline text,
  app_fee text,
  tuition text,
  room_board text,
  scholarships jsonb default '[]'::jsonb,
  insights text,
  website_url text
);

alter table universities enable row level security;
drop policy if exists "Allow all access" on universities;
create policy "Allow all access" on universities for all using (true) with check (true);
