-- 1. Create Universities Table
create table if not exists universities (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  location text,
  deadline text,
  app_fee text,
  tuition text,
  room_board text,
  scholarships jsonb default '[]'::jsonb,
  insights text,
  website_url text
);

alter table universities enable row level security;
create policy "Allow all access" on universities for all using (true) with check (true);

-- 2. Recreate Applications Table
-- Dropping existing table to ensure schema matches requirements
drop table if exists applications;

create table applications (
  id uuid default gen_random_uuid() primary key,
  student_id bigint references students(id) on delete cascade not null, -- Changed to bigint to match students.id
  university_id text not null,
  university_name text not null,
  status text default 'Planning',
  documents jsonb default '[]'::jsonb,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table applications enable row level security;
create policy "Allow all access" on applications for all using (true) with check (true);
